### ISSUE TITLE
Error: undefined method `to_default_s' for Float

### ISSUE THREAD

**Issue by eliten00b** [skaes/time_bandits#24]
I'm using rails 6, puma 6 with ruby 2.7.6. After updating time_bandits to 0.12.6 (before 0.12.5) I get the following error. Tested also with version 0.13.0 same error.

```
Puma caught this error: undefined method `to_default_s' for 10650.03901:Float (NoMethodError)
/.gem/ruby/2.7.6/gems/time_bandits-0.13.0/lib/time_bandits/rack/logger.rb:50:in `started_request_message'
/.gem/ruby/2.7.6/gems/time_bandits-0.13.0/lib/time_bandits/rack/logger.rb:74:in `start'
/.gem/ruby/2.7.6/gems/time_bandits-0.13.0/lib/time_bandits/rack/logger.rb:31:in `call_app'
/.gem/ruby/2.7.6/gems/time_bandits-0.13.0/lib/time_bandits/rack/logger.rb:23:in `call'
/.gem/ruby/2.7.6/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/.gem/ruby/2.7.6/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/.gem/ruby/2.7.6/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/.gem/ruby/2.7.6/gems/request_store_rails-2.0.0/lib/request_store_rails/middleware.rb:17:in `call'
/.gem/ruby/2.7.6/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/.gem/ruby/2.7.6/gems/rack-2.2.3.1/lib/rack/method_override.rb:24:in `call'
/.gem/ruby/2.7.6/gems/rack-2.2.3.1/lib/rack/runtime.rb:22:in `call'
/.gem/ruby/2.7.6/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
/.gem/ruby/2.7.6/gems/activesupport-6.0.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/app/middleware/meta_cat_redirect.rb:26:in `call'
/.gem/ruby/2.7.6/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/.gem/ruby/2.7.6/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/.gem/ruby/2.7.6/gems/rack-2.2.3.1/lib/rack/sendfile.rb:110:in `call'
/.gem/ruby/2.7.6/gems/actionpack-6.0.5.1/lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
/.gem/ruby/2.7.6/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiler.rb:393:in `call'
/.gem/ruby/2.7.6/gems/webpacker-5.4.3/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
/.gem/ruby/2.7.6/gems/rack-proxy-0.7.0/lib/rack/proxy.rb:63:in `call'
/.gem/ruby/2.7.6/gems/railties-6.0.5.1/lib/rails/engine.rb:527:in `call'
/.gem/ruby/2.7.6/gems/railties-6.0.5.1/lib/rails/railtie.rb:190:in `public_send'
/.gem/ruby/2.7.6/gems/railties-6.0.5.1/lib/rails/railtie.rb:190:in `method_missing'
/.gem/ruby/2.7.6/gems/puma-6.0.0/lib/puma/configuration.rb:268:in `call'
/.gem/ruby/2.7.6/gems/puma-6.0.0/lib/puma/request.rb:89:in `block in handle_request'
/.gem/ruby/2.7.6/gems/puma-6.0.0/lib/puma/thread_pool.rb:343:in `with_force_shutdown'
/.gem/ruby/2.7.6/gems/puma-6.0.0/lib/puma/request.rb:88:in `handle_request'
/.gem/ruby/2.7.6/gems/puma-6.0.0/lib/puma/server.rb:430:in `process_client'
/.gem/ruby/2.7.6/gems/puma-6.0.0/lib/puma/server.rb:233:in `block in run'
/.gem/ruby/2.7.6/gems/puma-6.0.0/lib/puma/thread_pool.rb:150:in `block in spawn_thread'
```

**Comment by skaes** [comment]
My bad. Should be fixed in latest release: 0.13.1.
